# Generated by Django 3.1.7 on 2021-09-26 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210926_1534'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_gitLink',
            field=models.URLField(null=True, verbose_name='git link'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_token_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.token'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_weiboLink',
            field=models.URLField(null=True, verbose_name='weibo link'),
        ),
    ]
