# Generated by Django 3.1.7 on 2021-04-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210412_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_sing',
            field=models.CharField(blank=True, max_length=150, verbose_name='nick name'),
        ),
    ]
