# Generated by Django 3.1.12 on 2021-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_transaction_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdk', models.CharField(max_length=1025)),
                ('amount', models.IntegerField(default=0)),
                ('is_used', models.IntegerField(default=0)),
            ],
        ),
    ]
