# Generated by Django 3.1.12 on 2021-08-21 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
