# Generated by Django 3.1.7 on 2021-03-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_delete',
            field=models.IntegerField(default=0),
        ),
    ]
