# Generated by Django 3.1.7 on 2021-09-26 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('running_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='aimodel',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
