# Generated by Django 3.1.7 on 2021-03-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='ai_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
