# Generated by Django 3.2 on 2021-04-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='ai_introduction',
            field=models.TextField(null=True, verbose_name='ai introduction'),
        ),
    ]
