# Generated by Django 3.1.12 on 2021-08-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_aimodel_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
            ],
        ),
    ]
