# Generated by Django 3.1.12 on 2021-07-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='ai_published',
            field=models.IntegerField(default=0),
        ),
    ]
