# Generated by Django 3.1.12 on 2021-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210626_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aimodel',
            old_name='ai_introduction',
            new_name='ai_true_description',
        ),
        migrations.AddField(
            model_name='task',
            name='ai_name',
            field=models.CharField(default='default ai name', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='training_material_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='ai_name',
            field=models.CharField(default='default ai name', max_length=100),
        ),
    ]
