# Generated by Django 3.1.12 on 2021-07-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210718_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='ai_author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='ai_frozen',
            field=models.IntegerField(default=0),
        ),
    ]
