# Generated by Django 3.1.12 on 2021-07-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210704_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='training_material_count',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='training_material_count',
            field=models.IntegerField(default=0),
        ),
    ]
