# Generated by Django 3.1.12 on 2021-07-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20210705_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='ai_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
