# Generated by Django 3.1.12 on 2021-07-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20210705_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='ai_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='ai_name',
            field=models.CharField(default='AI_NAME', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='ai_name',
            field=models.CharField(default='AI_NAME', max_length=100),
        ),
    ]
