# Generated by Django 3.1.7 on 2021-03-12 12:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=1025, verbose_name='file name')),
                ('file_bin', models.BinaryField()),
                ('file_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
